# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0f1b69c366dfdd9be77bbc2e1fcade37276311e9c7361b7d8a63aecf5e10aa3ed1a0c4845eb9ed86c4a650a12a127e433f28cb9b6a96e5b8635b7848294551e

test:
  secret_key_base: b3c5e03f220e0995cb0bbb61271cb5748531379d2ce494c5f549de3347478650a4fcbdcea50408ed3b968708c4602b37c488db4e7ef0076f3121fc19ddd4aca6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
